### ISSUE TITLE
Unable Push ALL items to current connection

### ISSUE THREAD

**Issue by ravikadri** [microsoftgraph/msgraph-search-connector-sample#12]
@[jasonjoh](https://github.com/microsoftgraph/msgraph-search-connector-sample/commits?author=jasonjoh)

May be you can help/suggest. I download and followed the instructions. 

Able to create a new connection and schema. But when i try to push items(option 7), i get the below error. Any hints what could be wrong here.

![image](https://user-images.githubusercontent.com/104390320/177579007-58e0ed7d-50af-4b37-9969-3867db7cf8f8.png)

-Ravi

**Comment by jasonjoh** [comment]
I apologize for the lack of response. This sample was omitted from the list of samples to monitor and maintain. I suspect this error is due to the code being outdated. I'm going to be updating this sample in the next day or so with the latest dependencies, so hopefully that will clear up your issue.

**Comment by jasonjoh** [comment]
Closing since the code has been updated. Let me know if that didn't resolve your issue.
